# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 22:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestMapLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_time', models.DateTimeField(auto_now_add=True)),
                ('operation', models.CharField(max_length=32)),
                ('ip_address', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'investmap_logs',
            },
        ),
        migrations.CreateModel(
            name='InvestMapObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('description', models.CharField(max_length=1000, verbose_name='Опис')),
                ('price', models.CharField(max_length=16, verbose_name='Ціна')),
                ('address', models.CharField(max_length=100, verbose_name='Адреса')),
                ('metrics', models.CharField(max_length=50, verbose_name='Площа')),
                ('contacts', models.CharField(max_length=100, verbose_name='Контакти')),
                ('project_type', models.CharField(choices=[('fb', 'Приміщення'), ('fa', 'Ділянка'), ('cp', 'Інвестиційний проект')], default=('fb', 'Приміщення'), max_length=2, verbose_name="Тип об'єкту")),
                ('object_type', models.IntegerField(choices=[(0, 'Приміщення'), (1, 'Ділянка')], default=0, verbose_name="Тип об'єкта")),
                ('image', models.ImageField(upload_to='investmap/', verbose_name='')),
            ],
            options={
                'db_table': 'investmap_objects',
            },
        ),
        migrations.CreateModel(
            name='InvestMapPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_lon', models.CharField(max_length=64)),
                ('map_lat', models.CharField(max_length=64)),
                ('investmap_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investmap.InvestMapObject')),
            ],
            options={
                'db_table': 'investmap_points',
            },
        ),
        migrations.CreateModel(
            name='ObjectHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва')),
                ('address', models.CharField(max_length=100, verbose_name='Адреса')),
            ],
            options={
                'db_table': 'investmap_holders',
            },
        ),
        migrations.AddField(
            model_name='investmapobject',
            name='object_holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investmap.ObjectHolder', verbose_name='Власник'),
        ),
        migrations.AddField(
            model_name='investmaplog',
            name='investmap_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='investmap.InvestMapObject'),
        ),
        migrations.AddField(
            model_name='investmaplog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
