# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 23:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investmap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmapobject',
            name='image',
        ),
        migrations.RemoveField(
            model_name='investmapobject',
            name='project_type',
        ),
    ]
